spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 83627496301-rejgn0jmprl5954vbhdi7rq0m6aa0eag.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub